//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watermelon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watermelon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutLab {
            get {
                return ResourceManager.GetString("aboutLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new graphic watermark.
        /// </summary>
        public static string addNewGraphicWatermarkTip {
            get {
                return ResourceManager.GetString("addNewGraphicWatermarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new text watermark.
        /// </summary>
        public static string addNewTextWatermarkTip {
            get {
                return ResourceManager.GetString("addNewTextWatermarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add new watermark.
        /// </summary>
        public static string addWatermarkTip {
            get {
                return ResourceManager.GetString("addWatermarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All watermarks.
        /// </summary>
        public static string allWatermarks {
            get {
                return ResourceManager.GetString("allWatermarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Marcin Włodarz.
        /// </summary>
        public static string authorName {
            get {
                return ResourceManager.GetString("authorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of Watermelon.
        /// </summary>
        public static string availableNewVersion {
            get {
                return ResourceManager.GetString("availableNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browseDirLab {
            get {
                return ResourceManager.GetString("browseDirLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the folder for saving files.
        /// </summary>
        public static string browseFolderTip {
            get {
                return ResourceManager.GetString("browseFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browseLab {
            get {
                return ResourceManager.GetString("browseLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the source graphic watermark.
        /// </summary>
        public static string browseTip {
            get {
                return ResourceManager.GetString("browseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string captionLabel {
            get {
                return ResourceManager.GetString("captionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark text.
        /// </summary>
        public static string captionTip {
            get {
                return ResourceManager.GetString("captionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string clearButton {
            get {
                return ResourceManager.GetString("clearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes all images from the collection.
        /// </summary>
        public static string clearTip {
            get {
                return ResourceManager.GetString("clearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to update..
        /// </summary>
        public static string clickToUpdate {
            get {
                return ResourceManager.GetString("clickToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string colorLab {
            get {
                return ResourceManager.GetString("colorLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color.
        /// </summary>
        public static string colorTip {
            get {
                return ResourceManager.GetString("colorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the image from the collection.
        /// </summary>
        public static string deleteTip {
            get {
                return ResourceManager.GetString("deleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want save changes in.
        /// </summary>
        public static string DoYouWantSaveChanges {
            get {
                return ResourceManager.GetString("DoYouWantSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current project?.
        /// </summary>
        public static string doYouWantSaveCurrentProject {
            get {
                return ResourceManager.GetString("doYouWantSaveCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want save new project?.
        /// </summary>
        public static string doYouWantSaveNewProject {
            get {
                return ResourceManager.GetString("doYouWantSaveNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the project?.
        /// </summary>
        public static string doYouWantSaveProject {
            get {
                return ResourceManager.GetString("doYouWantSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string exampleImage {
            get {
                return ResourceManager.GetString("exampleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example text.
        /// </summary>
        public static string exampleText {
            get {
                return ResourceManager.GetString("exampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string fileLab {
            get {
                return ResourceManager.GetString("fileLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string fontLab {
            get {
                return ResourceManager.GetString("fontLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font.
        /// </summary>
        public static string fontTip {
            get {
                return ResourceManager.GetString("fontTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string graphicTypeWatermark {
            get {
                return ResourceManager.GetString("graphicTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string heightLab {
            get {
                return ResourceManager.GetString("heightLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the height of the watermark in px.
        /// </summary>
        public static string heightTip {
            get {
                return ResourceManager.GetString("heightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helpLab {
            get {
                return ResourceManager.GetString("helpLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add files.
        /// </summary>
        public static string imagesAddFiles {
            get {
                return ResourceManager.GetString("imagesAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add images.
        /// </summary>
        public static string imagesAddFilesTip {
            get {
                return ResourceManager.GetString("imagesAddFilesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel to add images.
        /// </summary>
        public static string imagesPanelTip {
            get {
                return ResourceManager.GetString("imagesPanelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the program..
        /// </summary>
        public static string langCheckedMessage {
            get {
                return ResourceManager.GetString("langCheckedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names of output files: &quot;original name&quot; +.
        /// </summary>
        public static string nameResultFiles {
            get {
                return ResourceManager.GetString("nameResultFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string newLab {
            get {
                return ResourceManager.GetString("newLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string newWatermark {
            get {
                return ResourceManager.GetString("newWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next image.
        /// </summary>
        public static string nextImageTip {
            get {
                return ResourceManager.GetString("nextImageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no images to save!.
        /// </summary>
        public static string noImagesMessage {
            get {
                return ResourceManager.GetString("noImagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no watermarks!.
        /// </summary>
        public static string noWatermarksMessage {
            get {
                return ResourceManager.GetString("noWatermarksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only marked.
        /// </summary>
        public static string onlyMarked {
            get {
                return ResourceManager.GetString("onlyMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off.
        /// </summary>
        public static string onOff {
            get {
                return ResourceManager.GetString("onOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        public static string opacityLab {
            get {
                return ResourceManager.GetString("opacityLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the opacity of the watermark.
        /// </summary>
        public static string opacityTip {
            get {
                return ResourceManager.GetString("opacityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string openLab {
            get {
                return ResourceManager.GetString("openLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string openProjectLab {
            get {
                return ResourceManager.GetString("openProjectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open watermark file.
        /// </summary>
        public static string openTip {
            get {
                return ResourceManager.GetString("openTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string positionLab {
            get {
                return ResourceManager.GetString("positionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the arrow to set the position of the watermark.
        /// </summary>
        public static string positionTip {
            get {
                return ResourceManager.GetString("positionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the image in the default program.
        /// </summary>
        public static string previewTip {
            get {
                return ResourceManager.GetString("previewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous image.
        /// </summary>
        public static string previousImageTip {
            get {
                return ResourceManager.GetString("previousImageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project saved:.
        /// </summary>
        public static string projectSaved {
            get {
                return ResourceManager.GetString("projectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all watermarks to a file.
        /// </summary>
        public static string saveAllWatermarksTip {
            get {
                return ResourceManager.GetString("saveAllWatermarksTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string saveAsLab {
            get {
                return ResourceManager.GetString("saveAsLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save files.
        /// </summary>
        public static string saveButtonTip {
            get {
                return ResourceManager.GetString("saveButtonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save files in:.
        /// </summary>
        public static string saveFilesIn {
            get {
                return ResourceManager.GetString("saveFilesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string saveLab {
            get {
                return ResourceManager.GetString("saveLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the currently selected watermark to a file.
        /// </summary>
        public static string saveOnlyMarkedTip {
            get {
                return ResourceManager.GetString("saveOnlyMarkedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings panel.
        /// </summary>
        public static string savePanelTip {
            get {
                return ResourceManager.GetString("savePanelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string saveProjectLab {
            get {
                return ResourceManager.GetString("saveProjectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to save watermarks..
        /// </summary>
        public static string saveWatermarkTip {
            get {
                return ResourceManager.GetString("saveWatermarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site:.
        /// </summary>
        public static string siteLab {
            get {
                return ResourceManager.GetString("siteLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string sizeLab {
            get {
                return ResourceManager.GetString("sizeLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the font size.
        /// </summary>
        public static string sizeTip {
            get {
                return ResourceManager.GetString("sizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string sourceLab {
            get {
                return ResourceManager.GetString("sourceLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save completed successfully. Recorded images:.
        /// </summary>
        public static string successfulSavedMessage {
            get {
                return ResourceManager.GetString("successfulSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text in this field will be added to the name of the original file.
        /// </summary>
        public static string suffixTip {
            get {
                return ResourceManager.GetString("suffixTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string textTypeWatermark {
            get {
                return ResourceManager.GetString("textTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string tutorialLab {
            get {
                return ResourceManager.GetString("tutorialLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        public static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermarks settings panel.
        /// </summary>
        public static string watermarkPanelTip {
            get {
                return ResourceManager.GetString("watermarkPanelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermelon version:.
        /// </summary>
        public static string watermelonVersion {
            get {
                return ResourceManager.GetString("watermelonVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string widthLab {
            get {
                return ResourceManager.GetString("widthLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the width of the watermark in px.
        /// </summary>
        public static string widthTip {
            get {
                return ResourceManager.GetString("widthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change thumbnail size.
        /// </summary>
        public static string zoomTip {
            get {
                return ResourceManager.GetString("zoomTip", resourceCulture);
            }
        }
    }
}
